CREATE TABLE funding_source (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  source_id UUID NOT NULL,
  project_code VARCHAR(50) NOT NULL,
  total_budget NUMERIC(18, 2) NOT NULL,
  available_budget NUMERIC(18, 2) NOT NULL,
  burn_rate NUMERIC(5, 2),
  created_by_user VARCHAR(255)
);

CREATE UNIQUE INDEX uq_funding_source_source_id ON funding_source (source_id);

