CREATE TABLE legal_contract (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  contract_id UUID NOT NULL,
  relationship_id UUID NOT NULL,
  contract_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  project_id UUID,
  employment_cond VARCHAR(2),
  tacita_reconduccion_alert_sent BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX idx_legal_contract_contract_id ON legal_contract (contract_id);
CREATE INDEX idx_legal_contract_tenant_id ON legal_contract (tenant_id);
CREATE INDEX idx_legal_contract_status ON legal_contract (status);

