CREATE TABLE tax_form_110 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  form_id UUID NOT NULL,
  person_id UUID NOT NULL,
  total_declared NUMERIC(15, 2) NOT NULL,
  verified_credit NUMERIC(15, 2) NOT NULL,
  doc_id UUID,
  period_year INTEGER NOT NULL,
  period_month INTEGER NOT NULL,
  created_by_user VARCHAR(255)
);

CREATE UNIQUE INDEX uq_tax_form_110_form_id ON tax_form_110 (form_id);

