-- Flyway Migration: V20260524164501__init_iam_domain
-- Description: Initialize Identity & Access Management (IAM) tables

-- 1. iam_module Table
CREATE TABLE iam_module (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  code VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

-- 2. iam_action Table
CREATE TABLE iam_action (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  code VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

-- 3. iam_resource Table
CREATE TABLE iam_resource (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  code VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  module_id BIGINT NOT NULL,
  CONSTRAINT fk_iam_resource_module FOREIGN KEY (module_id) REFERENCES iam_module (id)
);

-- 4. iam_field Table
CREATE TABLE iam_field (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  resource_id BIGINT NOT NULL,
  CONSTRAINT fk_iam_field_resource FOREIGN KEY (resource_id) REFERENCES iam_resource (id)
);

-- 5. iam_role Table
CREATE TABLE iam_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255)
);

-- 6. iam_user Table
CREATE TABLE iam_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL
);

-- 7. iam_user_roles (ManyToMany Join Table)
CREATE TABLE iam_user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_iam_user_roles_user FOREIGN KEY (user_id) REFERENCES iam_user (id),
  CONSTRAINT fk_iam_user_roles_role FOREIGN KEY (role_id) REFERENCES iam_role (id)
);

-- 8. iam_permission Table
CREATE TABLE iam_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  role_id BIGINT NOT NULL,
  module_id BIGINT NOT NULL,
  resource_id BIGINT NOT NULL,
  action_id BIGINT NOT NULL,
  field_id BIGINT,
  CONSTRAINT fk_iam_permission_role FOREIGN KEY (role_id) REFERENCES iam_role (id),
  CONSTRAINT fk_iam_permission_module FOREIGN KEY (module_id) REFERENCES iam_module (id),
  CONSTRAINT fk_iam_permission_resource FOREIGN KEY (resource_id) REFERENCES iam_resource (id),
  CONSTRAINT fk_iam_permission_action FOREIGN KEY (action_id) REFERENCES iam_action (id),
  CONSTRAINT fk_iam_permission_field FOREIGN KEY (field_id) REFERENCES iam_field (id)
);
