CREATE TABLE iam_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL
);

CREATE TABLE iam_user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_iam_user_roles_user
    FOREIGN KEY (user_id) REFERENCES iam_user (id),
  CONSTRAINT fk_iam_user_roles_role
    FOREIGN KEY (role_id) REFERENCES iam_role (id)
);

CREATE INDEX idx_iam_user_roles_role_id ON iam_user_roles (role_id);

