CREATE TABLE health_provider (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  provider_id UUID NOT NULL,
  registration_no VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_by_user VARCHAR(255)
);

CREATE UNIQUE INDEX uq_health_provider_provider_id ON health_provider (provider_id);

