CREATE TABLE legal_contract_addendum (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  addendum_id UUID NOT NULL,
  contract_id UUID NOT NULL,
  status VARCHAR(20) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NOT NULL,
  basic_salary NUMERIC(15, 2),
  total_earned_proj NUMERIC(15, 2),
  net_salary_proj NUMERIC(15, 2),
  currency VARCHAR(3),
  smn_applied NUMERIC(15, 2),
  tax_regime VARCHAR(50),
  infocal_active BOOLEAN,
  CONSTRAINT fk_legal_addendum_contract
    FOREIGN KEY (contract_id) REFERENCES legal_contract (contract_id)
);

CREATE UNIQUE INDEX idx_legal_addendum_addendum_id ON legal_contract_addendum (addendum_id);
CREATE INDEX idx_legal_addendum_contract_id ON legal_contract_addendum (contract_id);
CREATE INDEX idx_legal_addendum_tenant_id ON legal_contract_addendum (tenant_id);

