CREATE TABLE legal_policy_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  policy_id UUID NOT NULL,
  policy_name VARCHAR(100) NOT NULL,
  description TEXT
);

CREATE UNIQUE INDEX idx_legal_policy_rule_policy_id ON legal_policy_rule (policy_id);
CREATE INDEX idx_legal_policy_rule_tenant_id ON legal_policy_rule (tenant_id);

CREATE TABLE legal_policy_threshold (
  policy_id UUID NOT NULL,
  threshold_value NUMERIC(15, 4),
  effective_date DATE,
  CONSTRAINT fk_legal_policy_threshold_policy
    FOREIGN KEY (policy_id) REFERENCES legal_policy_rule (policy_id)
);

