CREATE TABLE iam_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  role_id BIGINT NOT NULL,
  module_id BIGINT NOT NULL,
  resource_id BIGINT NOT NULL,
  action_id BIGINT NOT NULL,
  field_id BIGINT,
  CONSTRAINT fk_iam_permission_role
    FOREIGN KEY (role_id) REFERENCES iam_role (id),
  CONSTRAINT fk_iam_permission_module
    FOREIGN KEY (module_id) REFERENCES iam_module (id),
  CONSTRAINT fk_iam_permission_resource
    FOREIGN KEY (resource_id) REFERENCES iam_resource (id),
  CONSTRAINT fk_iam_permission_action
    FOREIGN KEY (action_id) REFERENCES iam_action (id),
  CONSTRAINT fk_iam_permission_field
    FOREIGN KEY (field_id) REFERENCES iam_field (id)
);

