CREATE TABLE labor_cost_split (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  split_id UUID NOT NULL,
  unit_id UUID NOT NULL,
  percentage NUMERIC(5, 2) NOT NULL,
  effective_date DATE NOT NULL,
  funding_source_id BIGINT NOT NULL,
  CONSTRAINT fk_labor_cost_split_funding_source
    FOREIGN KEY (funding_source_id) REFERENCES funding_source (id)
);

CREATE UNIQUE INDEX uq_labor_cost_split_split_id ON labor_cost_split (split_id);

