CREATE TABLE iam_field (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  resource_id BIGINT NOT NULL,
  CONSTRAINT fk_iam_field_resource
    FOREIGN KEY (resource_id) REFERENCES iam_resource (id)
);

