-- Flyway Migration: V20260524173000__init_audit_outbox
-- Description: Initialize audit log and shared outbox tables

-- 1. audit_log Table
CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  entity VARCHAR(255) NOT NULL,
  entity_id VARCHAR(255) NOT NULL,
  user_id VARCHAR(255),
  tenant_id VARCHAR(255),
  occurred_at TIMESTAMP
);

-- 2. shared_event_outbox Table
CREATE TABLE shared_event_outbox (
  event_id UUID PRIMARY KEY,
  aggregate_type VARCHAR(50),
  aggregate_id UUID,
  type VARCHAR(100) NOT NULL,
  payload TEXT NOT NULL,
  state VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  processed_at TIMESTAMP,
  error_log TEXT
);

