CREATE TABLE social_security_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  ssa_id UUID NOT NULL,
  person_id UUID NOT NULL,
  gestora_code VARCHAR(30) NOT NULL,
  contribution_rate NUMERIC(5, 4) NOT NULL,
  last_contribution DATE,
  created_by_user VARCHAR(255)
);

CREATE UNIQUE INDEX uq_social_security_account_ssa_id ON social_security_account (ssa_id);

