CREATE TABLE time_deviation_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  deviation_id UUID NOT NULL,
  ledger_id BIGINT NOT NULL,
  deviation_type VARCHAR(40) NOT NULL,
  deviation_minutes INTEGER NOT NULL,
  resolution_status VARCHAR(40) NOT NULL,
  detected_at TIMESTAMP NOT NULL,
  resolved_at TIMESTAMP,
  resolved_by UUID,
  reason_note TEXT,
  secondary_approver_id UUID,
  CONSTRAINT fk_time_deviation_ledger FOREIGN KEY (ledger_id) REFERENCES attendance_ledger (id)
);

