CREATE TABLE punch_attempt_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  attempt_id UUID NOT NULL,
  device_id BIGINT NOT NULL,
  attempted_at TIMESTAMP NOT NULL,
  relationship_id UUID NOT NULL,
  auth_method VARCHAR(20) NOT NULL,
  auth_result VARCHAR(30) NOT NULL,
  security_incident BOOLEAN NOT NULL,
  incident_escalated_to UUID,
  CONSTRAINT fk_punch_attempt_log_device FOREIGN KEY (device_id) REFERENCES clocking_device (id)
);

