CREATE TABLE timesheet_period (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  period_id UUID NOT NULL,
  org_unit_id UUID NOT NULL,
  period_type VARCHAR(20) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  grace_period_end TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL,
  closed_at TIMESTAMP,
  closed_by UUID,
  closure_type VARCHAR(10),
  payroll_event_emitted_at TIMESTAMP,
  CONSTRAINT uq_timesheet_period_period_id UNIQUE (period_id)
);

