CREATE TABLE payroll_handoff_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  handoff_id UUID NOT NULL,
  period_id BIGINT NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  checksum VARCHAR(128) NOT NULL,
  CONSTRAINT uq_payroll_handoff_period UNIQUE (period_id),
  CONSTRAINT uq_payroll_handoff_id UNIQUE (handoff_id),
  CONSTRAINT fk_payroll_handoff_period FOREIGN KEY (period_id) REFERENCES timesheet_period (id)
);

CREATE TABLE payroll_handoff_employee_record (
  handoff_id UUID NOT NULL,
  relationship_id UUID NOT NULL,
  regular_hours_total NUMERIC(8, 2) NOT NULL,
  overtime_hours_total NUMERIC(8, 2) NOT NULL,
  night_hours_total NUMERIC(8, 2) NOT NULL,
  holiday_hours_total NUMERIC(8, 2) NOT NULL,
  unjustified_absences INTEGER NOT NULL,
  remote_work_days INTEGER NOT NULL,
  data_quality_flag VARCHAR(30) NOT NULL,
  PRIMARY KEY (handoff_id, relationship_id),
  CONSTRAINT fk_payroll_handoff_record FOREIGN KEY (handoff_id)
    REFERENCES payroll_handoff_package (handoff_id)
);

