CREATE TABLE device_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  audit_log_id UUID NOT NULL,
  device_id BIGINT NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  actor_id VARCHAR(100),
  occurred_at TIMESTAMP NOT NULL,
  description TEXT,
  CONSTRAINT fk_device_audit_log_device FOREIGN KEY (device_id) REFERENCES clocking_device (id)
);

