CREATE TABLE biometric_enrollment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  enrollment_id UUID NOT NULL,
  device_id BIGINT NOT NULL,
  relationship_id UUID NOT NULL,
  biometric_type VARCHAR(20) NOT NULL,
  template_hash VARCHAR(128) NOT NULL,
  template_quality_score NUMERIC(4, 2) NOT NULL,
  status VARCHAR(20) NOT NULL,
  enrolled_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP,
  revocation_reason VARCHAR(30),
  CONSTRAINT uk_enrollment_relationship_type_active UNIQUE (relationship_id, biometric_type, status, tenant_id),
  CONSTRAINT fk_biometric_enrollment_device FOREIGN KEY (device_id) REFERENCES clocking_device (id)
);

