CREATE TABLE daily_consolidation_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  summary_id UUID NOT NULL,
  period_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  total_scheduled INTEGER NOT NULL,
  total_attended INTEGER NOT NULL,
  total_no_shows INTEGER NOT NULL,
  total_exceptions_pending INTEGER NOT NULL,
  total_regular_hours NUMERIC(8, 2) NOT NULL,
  total_overtime_hours NUMERIC(8, 2) NOT NULL,
  total_night_hours NUMERIC(8, 2) NOT NULL,
  calculated_at TIMESTAMP NOT NULL,
  CONSTRAINT uq_daily_consolidation_summary_id UNIQUE (summary_id),
  CONSTRAINT fk_daily_consolidation_period FOREIGN KEY (period_id) REFERENCES timesheet_period (id)
);

