package com.solveria.core.dossier.domain.exception;

public enum DossierErrorCode {
  ASSET_DESCRIPTOR_REQUIRED,
  ASSIGNMENT_ID_REQUIRED,
  DOCUMENT_ID_REQUIRED,
  EMPLOYEE_ID_REQUIRED,
  RELATIONSHIP_ID_REQUIRED,
  COMMAND_INVALID,
  INVENTORY_REQUIRED,
  MEMORANDUM_ACK_CONTENT_REQUIRED,
  MEMORANDUM_ACK_FILE_NAME_REQUIRED,
  PERFORMANCE_PERIOD_REQUIRED,
  PERFORMANCE_SCORE_REQUIRED,
  SKILL_NAME_REQUIRED,
  PROFIENCY_REQUIRED,
  DISCIPLINARY_REASON_REQUIRED,
  DISCIPLINARY_SEVERITY_REQUIRED,
  DISCIPLINARY_EVIDENCE_REQUIRED,
  DISCIPLINARY_EVIDENCE_FILE_NAME_REQUIRED
}
