CREATE TABLE prl_dispersion_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  dispersion_file_id UUID,
  run_ref UUID,
  bank_entity_ref UUID,
  status VARCHAR(255),
  total_amount NUMERIC(19, 4),
  record_count INTEGER,
  file_hash VARCHAR(255)
);

