CREATE TABLE prl_payroll_period (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  period_id UUID NOT NULL,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  cutoff_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  holiday_calendar_ref UUID,
  CONSTRAINT uq_prl_payroll_period_period_id UNIQUE (period_id)
);

