CREATE TABLE prl_payment_method (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  payment_method_id UUID NOT NULL,
  channel VARCHAR(30) NOT NULL,
  is_default BOOLEAN NOT NULL,
  CONSTRAINT uq_prl_payment_method_payment_method_id UNIQUE (payment_method_id)
);

