CREATE TABLE prl_payroll_line (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  line_id UUID,
  run_id BIGINT,
  employee_id UUID,
  basic_salary NUMERIC(19, 4),
  total_earned NUMERIC(19, 4),
  rc_iva_retained NUMERIC(19, 4),
  gestora_retained NUMERIC(19, 4),
  other_deductions NUMERIC(19, 4),
  net_payable NUMERIC(19, 4),
  CONSTRAINT fk_prl_payroll_line_run FOREIGN KEY (run_id) REFERENCES prl_payroll_run (id)
);

