CREATE TABLE prl_payroll_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  group_id UUID NOT NULL,
  group_code VARCHAR(50) NOT NULL,
  type_code VARCHAR(30) NOT NULL,
  description VARCHAR(255),
  CONSTRAINT uq_prl_payroll_group_group_id UNIQUE (group_id)
);

