CREATE TABLE prl_deduction_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  deduction_record_id UUID NOT NULL,
  employee_id UUID NOT NULL,
  period_ref UUID NOT NULL,
  deduction_type VARCHAR(50) NOT NULL,
  amount NUMERIC(19, 4) NOT NULL,
  is_automatic BOOLEAN NOT NULL,
  CONSTRAINT uq_prl_deduction_record_deduction_record_id UNIQUE (deduction_record_id)
);

