CREATE TABLE prl_bank_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  bank_entity_id UUID NOT NULL,
  bank_code VARCHAR(30) NOT NULL,
  name VARCHAR(150) NOT NULL,
  file_format VARCHAR(100),
  CONSTRAINT uq_prl_bank_entity_bank_entity_id UNIQUE (bank_entity_id)
);

