CREATE TABLE prl_payroll_approval (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  payroll_approval_id UUID,
  run_ref UUID NOT NULL,
  status VARCHAR(255) NOT NULL,
  creator_ref UUID NOT NULL,
  reviewer_ref UUID,
  approver_ref UUID,
  sod_violation_flag BOOLEAN NOT NULL
);

