CREATE TABLE prl_payroll_closure (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  payroll_closure_id UUID,
  run_ref UUID NOT NULL,
  status VARCHAR(255) NOT NULL,
  integrity_hash VARCHAR(255)
);

