CREATE TABLE prl_payroll_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  payroll_run_id UUID,
  period_ref UUID,
  group_ref UUID,
  run_type VARCHAR(255),
  status VARCHAR(255)
);

