package com.solveria.core.dossier.domain.event;

public enum DossierEventType {
  DOCUMENT_RECORDED,
  DOCUMENT_VALIDATION_REJECTED,
  DOCENT_ACADEMIC_TITLE_VERIFIED,
  HEALTH_CARD_EXPIRATION_WARNING,
  MANDATORY_COMPLIANCE_DOC_MISSING,
  ELIGIBILITY_SUSPENDED_BY_COMPLIANCE,
  ELIGIBILITY_RESTORED,
  MEMORANDUM_ISSUED,
  DISCIPLINARY_THRESHOLD_REACHED,
  MEMORANDUM_ACKNOWLEDGED,
  ASSET_LOANED_TO_WORKER,
  ASSET_TRANSFER_REQUIRED,
  ASSET_RETURNED,
  ASSET_DAMAGE_REPORTED,
  OFFBOARDING_BLOCKED_BY_ASSETS
}
