package com.solveria.core.accruals.domain.event;

public enum AccrualEventType {
  LEAVE_REQUEST_SUBMITTED,
  LEAVE_REQUEST_MANAGER_APPROVED,
  LEAVE_REQUEST_MANAGER_REJECTED,
  VACATION_BALANCE_THRESHOLD_LOW,
  ACCRUAL_BALANCE_DEDUCTED,
  RANK_UPGRADE_ELIGIBILITY_REACHED,
  QUINQUENIO_ELIGIBILITY_REACHED,
  QUINQUENIO_REQUESTED,
  QUINQUENIO_CALCULATION_FINALIZED,
  QUINQUENIO_PAYMENT_OVERDUE,
  QUINQUENIO_PAYMENT_PROCESSED
}
