CREATE TABLE sch_attendance_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  record_id UUID,
  relationship_id UUID NOT NULL,
  work_date DATE NOT NULL,
  is_closed BOOLEAN NOT NULL,
  status VARCHAR(255) NOT NULL,
  deviations JSONB
);

