CREATE TABLE sch_time_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  entry_id UUID,
  record_id BIGINT NOT NULL,
  punch_time TIMESTAMP NOT NULL,
  punch_type VARCHAR(255) NOT NULL,
  device_id VARCHAR(255),
  source VARCHAR(255),
  geo_validation JSONB,
  CONSTRAINT fk_sch_time_entry_record FOREIGN KEY (record_id) REFERENCES sch_attendance_record (id)
);

