CREATE TABLE sch_assigned_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT,
  tenant_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  last_modified_at TIMESTAMP,
  last_modified_by VARCHAR(255),
  shift_id UUID,
  plan_id BIGINT NOT NULL,
  relationship_id UUID NOT NULL,
  expected_start TIMESTAMP NOT NULL,
  expected_end TIMESTAMP NOT NULL,
  shift_type VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL,
  metadata JSONB,
  violations JSONB,
  CONSTRAINT fk_sch_assigned_shift_plan FOREIGN KEY (plan_id) REFERENCES sch_schedule_plan (id)
);

